### ISSUE TITLE
Not working, I don't know why

### ISSUE THREAD

**Issue by njaros** [lmalki-h/push_swap_tester#11]
I'm in the push_swap_tester directory and I press : sh tester.sh ../push_swap 5 5
not working :'(

list of input/output :

z4r10p7% sh tester.sh ../push_swap 5 5
error: could not find push_swap in ../push_swap 
z4r10p7% sh tester.sh ../ 5 5         
error: could not find checker in ../ 
z4r10p7% sh tester.sh .. 5 5 
error: could not find checker in .. 
z4r10p7% bash tester.sh ../push_swap 5 5
error: could not find push_swap in ../push_swap

**Comment by Hugothms** [comment]
In the command line "sh tester.sh ../push_swap 5 5", the path "../push_swap" is the path to the push swap directory and not the path to the executable.

Your folder structure should look like this:
/push_swap_tester
	tester.sh
	genstack.pl
	...
/push_swap		<-- Directory
	push_swap	<-- Executable
	...
