### ISSUE TITLE
you're not correctly generating numbers in your generating.pl

### ISSUE THREAD

**Issue by llefranc** [lmalki-h/push_swap_tester#2]
for( $num = 0; $num < $stacksize; ) {
	$n = int(srand() % ($max- $min) + $min);
	if (!(grep { $_ eq $n } @stack)) {
		push @stack, $n;
		**$num++;**
	}
}

this will fix the problem ;) you're still incrementing num even if the number already exist to avoid duplicate, so if you want to generate 100 number you will in fact generate something like 80 numbers ! 

otherwise your tester is really great :)

**Comment by louisabricot** [comment]
Thank you ! I had not seen this at all. Correction is on its way
