### ISSUE TITLE
Mean gets added up when using ranges

### ISSUE THREAD

**Issue by popohl** [lmalki-h/push_swap_tester#6]
When starting the tester with a range, the mean variable does not seem to be the actual mean:
![image](https://user-images.githubusercontent.com/52739393/112669170-ae2aa600-8e5f-11eb-9635-9b3ed46f76e8.png)

I think the problem is that the mean gets added up as the program goes, maybe resetting it to 0 at some point might help.

**Comment by louisabricot** [comment]
Thank you for the feedback ! I have resolved the issue
